import {
  TrackedSubject,
  SurveillanceNode,
  CCTVCameraFeed,
  MerkleAuditBlock,
  SovereignDID,
  VerifiableCredential,
  AutomatedAlertRule,
  ActiveAlertLog,
  PoliceStation,
  ThreatDispatchPacket,
  MostWantedFugitive,
  IPTrackerRecord,
} from '../types';

export const INITIAL_TRACKED_SUBJECTS: TrackedSubject[] = [
  {
    id: 'SUB-9082',
    fullName: 'Elena V. Rostova',
    alias: 'CIPHER_NIGHTINGALE',
    did: 'did:aegis:7f89d3a180429b61e29c',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face',
    nationalIdNumber: 'NL-8842-99120-A',
    threatLevel: 'CRITICAL_CODE_RED',
    geofenceStatus: 'BREACH_DETECTED',
    currentLocation: {
      lat: 52.379189,
      lng: 4.899431,
      altitudeMeters: 14.2,
      accuracyMeters: 1.8,
      headingDegrees: 142,
      speedKmh: 48.5,
      locationName: 'Amsterdam Centraal Station Perimeter (Zone 1A)',
      zoneId: 'ZONE_HIGH_SECURITY_ALPHA',
      timestamp: new Date(Date.now() - 45000).toISOString(),
    },
    locationHistory: [
      {
        lat: 52.3676,
        lng: 4.9041,
        altitudeMeters: 8.0,
        accuracyMeters: 3.2,
        headingDegrees: 350,
        speedKmh: 22.0,
        locationName: 'Waterlooplein Metro Crossing',
        zoneId: 'ZONE_TRANSIT_CORE',
        timestamp: new Date(Date.now() - 420000).toISOString(),
      },
      {
        lat: 52.3731,
        lng: 4.8924,
        altitudeMeters: 10.5,
        accuracyMeters: 2.1,
        headingDegrees: 45,
        speedKmh: 36.4,
        locationName: 'Dam Square Surveillance Intersection #12',
        zoneId: 'ZONE_COMMERCIAL_BETA',
        timestamp: new Date(Date.now() - 210000).toISOString(),
      },
      {
        lat: 52.379189,
        lng: 4.899431,
        altitudeMeters: 14.2,
        accuracyMeters: 1.8,
        headingDegrees: 142,
        speedKmh: 48.5,
        locationName: 'Amsterdam Centraal Station Perimeter (Zone 1A)',
        zoneId: 'ZONE_HIGH_SECURITY_ALPHA',
        timestamp: new Date(Date.now() - 45000).toISOString(),
      },
    ],
    bankcardTransactions: [
      {
        id: 'TX-99021',
        cardMask: '•••• 4419',
        network: 'VISA_SECURE',
        merchant: 'NS International Rail Ticketing - Brussels Eurostar Express',
        amount: 148.50,
        currency: 'EUR',
        terminalId: 'POS-AMS-CENTRAAL-T8',
        lat: 52.3789,
        lng: 4.8998,
        timestamp: new Date(Date.now() - 95000).toISOString(),
        isFlagged: true,
        flagReason: 'High-speed one-way transit booking post-geofence breach',
        authMethod: 'CONTACTLESS_NFC',
      },
      {
        id: 'TX-98914',
        cardMask: '•••• 4419',
        network: 'VISA_SECURE',
        merchant: 'ING Bank Global ATM Vault 41',
        amount: 800.00,
        currency: 'EUR',
        terminalId: 'ATM-DAM-402',
        lat: 52.3729,
        lng: 4.8931,
        timestamp: new Date(Date.now() - 240000).toISOString(),
        isFlagged: true,
        flagReason: 'Maximum daily emergency sovereign fiat withdrawal',
        authMethod: 'CHIP_PIN',
      },
    ],
    transitEvents: [
      {
        id: 'TR-7721',
        transitType: 'METRO_GATE',
        stationOrGate: 'Metro 52 Noord-Zuidlijn (Turnstile 04B)',
        routeId: 'M52-NORTHBOUND',
        passCardId: 'OV-CHIP-9902-88',
        lat: 52.3790,
        lng: 4.8996,
        timestamp: new Date(Date.now() - 50000).toISOString(),
        direction: 'ENTRY',
        biometricGateMatched: true,
        anomalyDetected: true,
      },
      {
        id: 'TR-7690',
        transitType: 'HIGH_SPEED_RAIL',
        stationOrGate: 'Platform 15b - High Speed Gate Intercept',
        routeId: 'THALYS-9328',
        passCardId: 'OV-CHIP-9902-88',
        lat: 52.3794,
        lng: 4.9002,
        timestamp: new Date(Date.now() - 15000).toISOString(),
        direction: 'ENTRY',
        biometricGateMatched: true,
        anomalyDetected: true,
      },
    ],
    biometrics: {
      irisHash: '0x9e88b22a0145cbf988941094038aee8c1',
      voiceprintHarmonicScore: 98.2,
      gaitCadenceFrequency: 1.84,
      faceEmbeddingVector: [0.84, -0.21, 0.44, 0.91, -0.12, 0.65, 0.77],
      faceMatchScore: 99.4,
      dnaMarkerReference: 'GEN-MARK-NL-EU-94829',
      lastScannedAt: new Date(Date.now() - 20000).toISOString(),
      govDatabaseRefId: 'INTERPOL-RED-2026-9921',
      govDatabaseStatus: 'WATCHLIST_RED_NOTICE',
    },
    assignedSecureNodeId: 'NODE-RELAY-01-AMS',
    e2eeSessionActive: true,
    lastTelemetryPing: new Date(Date.now() - 5000).toISOString(),
    notes: 'Suspect flagged by automated God\'s Eye optical neural vector at Platform 15. Attempting unauthorized international border crossing.',
    isLockedOn: true,
  },
  {
    id: 'SUB-4410',
    fullName: 'Dr. Tariq Al-Mansoor',
    alias: 'APEX_ARCHITECT',
    did: 'did:aegis:e44b89110294fcda3108',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face',
    nationalIdNumber: 'NL-4109-77281-B',
    threatLevel: 'HIGH',
    geofenceStatus: 'APPROACHING_BOUNDARY',
    currentLocation: {
      lat: 52.3601,
      lng: 4.8852,
      altitudeMeters: 5.4,
      accuracyMeters: 2.4,
      headingDegrees: 210,
      speedKmh: 14.2,
      locationName: 'Museumplein Quantum Research Labs',
      zoneId: 'ZONE_RESTRICTED_RESEARCH',
      timestamp: new Date(Date.now() - 30000).toISOString(),
    },
    locationHistory: [
      {
        lat: 52.3582,
        lng: 4.8814,
        altitudeMeters: 4.1,
        accuracyMeters: 3.1,
        headingDegrees: 180,
        speedKmh: 4.5,
        locationName: 'Van Baerlestraat Sensor Relay',
        zoneId: 'ZONE_RESTRICTED_RESEARCH',
        timestamp: new Date(Date.now() - 180000).toISOString(),
      },
      {
        lat: 52.3601,
        lng: 4.8852,
        altitudeMeters: 5.4,
        accuracyMeters: 2.4,
        headingDegrees: 210,
        speedKmh: 14.2,
        locationName: 'Museumplein Quantum Research Labs',
        zoneId: 'ZONE_RESTRICTED_RESEARCH',
        timestamp: new Date(Date.now() - 30000).toISOString(),
      },
    ],
    bankcardTransactions: [
      {
        id: 'TX-88190',
        cardMask: '•••• 1092',
        network: 'AEGIS_SOVEREIGN_PAY',
        merchant: 'CryoGen Secure Hardware Node Dispenser',
        amount: 4200.00,
        currency: 'EUR',
        terminalId: 'POS-CRYPTO-SEC-09',
        lat: 52.3599,
        lng: 4.8848,
        timestamp: new Date(Date.now() - 500000).toISOString(),
        isFlagged: false,
        authMethod: 'BIOMETRIC_TOUCH',
      },
    ],
    transitEvents: [
      {
        id: 'TR-6120',
        transitType: 'BUS_RAPID',
        stationOrGate: 'Museumplein Tram Line 5 Station',
        routeId: 'TRAM-05-SOUTH',
        passCardId: 'PASS-SOV-4410',
        lat: 52.3600,
        lng: 4.8850,
        timestamp: new Date(Date.now() - 200000).toISOString(),
        direction: 'ENTRY',
        biometricGateMatched: true,
        anomalyDetected: false,
      },
    ],
    biometrics: {
      irisHash: '0x10fa9831998ccb091834a991823efca4',
      voiceprintHarmonicScore: 94.7,
      gaitCadenceFrequency: 1.62,
      faceEmbeddingVector: [0.42, 0.88, -0.31, 0.19, 0.74, -0.45, 0.62],
      faceMatchScore: 98.1,
      dnaMarkerReference: 'GEN-MARK-NL-RES-5510',
      lastScannedAt: new Date(Date.now() - 60000).toISOString(),
      govDatabaseRefId: 'GOV-MIN-DEF-CLEAR-L4',
      govDatabaseStatus: 'CLASSIFIED_OPERATIVE',
    },
    assignedSecureNodeId: 'NODE-RELAY-04-RESEARCH',
    e2eeSessionActive: true,
    lastTelemetryPing: new Date(Date.now() - 10000).toISOString(),
    notes: 'Quantum cryptographic key custodian. High-value asset within designated research perimeter.',
    isLockedOn: false,
  },
  {
    id: 'SUB-2104',
    fullName: 'Lucas K. Vance',
    alias: 'SPECTRE_09',
    did: 'did:aegis:992014fbca109283401c',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face',
    nationalIdNumber: 'NL-1092-38190-C',
    threatLevel: 'GUARDED',
    geofenceStatus: 'WITHIN_PERIMETER',
    currentLocation: {
      lat: 52.3738,
      lng: 4.8899,
      altitudeMeters: 7.2,
      accuracyMeters: 1.2,
      headingDegrees: 90,
      speedKmh: 3.8,
      locationName: 'Singel Canal Financial Node District',
      zoneId: 'ZONE_FINANCIAL_NODE',
      timestamp: new Date(Date.now() - 20000).toISOString(),
    },
    locationHistory: [
      {
        lat: 52.3738,
        lng: 4.8899,
        altitudeMeters: 7.2,
        accuracyMeters: 1.2,
        headingDegrees: 90,
        speedKmh: 3.8,
        locationName: 'Singel Canal Financial Node District',
        zoneId: 'ZONE_FINANCIAL_NODE',
        timestamp: new Date(Date.now() - 20000).toISOString(),
      },
    ],
    bankcardTransactions: [
      {
        id: 'TX-77182',
        cardMask: '•••• 9102',
        network: 'MASTERCARD_CHIP',
        merchant: 'Sovereign Secure Coffee Node',
        amount: 4.80,
        currency: 'EUR',
        terminalId: 'POS-SNG-41',
        lat: 52.3739,
        lng: 4.8898,
        timestamp: new Date(Date.now() - 600000).toISOString(),
        isFlagged: false,
        authMethod: 'CONTACTLESS_NFC',
      },
    ],
    transitEvents: [
      {
        id: 'TR-4401',
        transitType: 'METRO_GATE',
        stationOrGate: 'Rokin Metro Station (Gate 02)',
        routeId: 'M52-SOUTH',
        passCardId: 'OV-CHIP-4419-01',
        lat: 52.3710,
        lng: 4.8930,
        timestamp: new Date(Date.now() - 1200000).toISOString(),
        direction: 'EXIT',
        biometricGateMatched: true,
        anomalyDetected: false,
      },
    ],
    biometrics: {
      irisHash: '0x88bb1904fc19280ab441991823efba77',
      voiceprintHarmonicScore: 91.5,
      gaitCadenceFrequency: 1.71,
      faceEmbeddingVector: [0.15, 0.44, 0.82, -0.40, 0.22, 0.91, -0.33],
      faceMatchScore: 97.8,
      dnaMarkerReference: 'GEN-MARK-NL-CIT-8821',
      lastScannedAt: new Date(Date.now() - 90000).toISOString(),
      govDatabaseRefId: 'GOV-CITIZEN-PASS-2026',
      govDatabaseStatus: 'VERIFIED_CITIZEN',
    },
    assignedSecureNodeId: 'NODE-RELAY-02-FINANCIAL',
    e2eeSessionActive: true,
    lastTelemetryPing: new Date(Date.now() - 15000).toISOString(),
    notes: 'Citizen node operator. Zero anomalous movements detected in past 72 hours.',
    isLockedOn: false,
  },
];

export const SURVEILLANCE_NODES: SurveillanceNode[] = [
  {
    id: 'NODE-RELAY-01-AMS',
    nodeName: 'AMS-CENTRAAL-ORBITAL-RADAR',
    type: 'CCTV_FACIAL_SCANNER',
    lat: 52.379189,
    lng: 4.899431,
    coverageRadiusMeters: 450,
    status: 'ALERT_LOCK',
    quantumShieldEnabled: true,
    packetThroughputKbps: 4820,
    connectedClients: 84,
    activeDetections: 14,
  },
  {
    id: 'NODE-RELAY-02-FINANCIAL',
    nodeName: 'DAM-SQUARE-SURVEILLANCE-HUB',
    type: 'RADAR_ARRAY',
    lat: 52.3731,
    lng: 4.8924,
    coverageRadiusMeters: 380,
    status: 'ENCRYPTED_STREAMING',
    quantumShieldEnabled: true,
    packetThroughputKbps: 3120,
    connectedClients: 142,
    activeDetections: 8,
  },
  {
    id: 'NODE-RELAY-03-WATERLOO',
    nodeName: 'WATERLOO-TRANSIT-BEACON',
    type: 'TRANSIT_SENSOR',
    lat: 52.3676,
    lng: 4.9041,
    coverageRadiusMeters: 300,
    status: 'ACTIVE',
    quantumShieldEnabled: true,
    packetThroughputKbps: 2240,
    connectedClients: 64,
    activeDetections: 4,
  },
  {
    id: 'NODE-RELAY-04-RESEARCH',
    nodeName: 'MUSEUMPLEIN-QUANTUM-SHIELD',
    type: 'GEOFENCE_BEACON',
    lat: 52.3601,
    lng: 4.8852,
    coverageRadiusMeters: 550,
    status: 'ENCRYPTED_STREAMING',
    quantumShieldEnabled: true,
    packetThroughputKbps: 5890,
    connectedClients: 39,
    activeDetections: 2,
  },
];

export const CCTV_CAMERA_FEEDS: CCTVCameraFeed[] = [
  {
    id: 'CAM-AMS-01-OPTICAL',
    cameraName: 'Platform 15B International Concourse HD-01',
    sector: 'SECTOR-1A-RAIL',
    lat: 52.3793,
    lng: 4.8995,
    resolution: '4K 60FPS (HDR Optical + IR)',
    fps: 60,
    feedType: 'NEURAL_LANDMARK',
    activeTargets: [
      {
        subjectId: 'SUB-9082',
        subjectName: 'Elena V. Rostova',
        boundingBox: { x: 38, y: 24, width: 28, height: 46 },
        matchConfidence: 99.4,
        trackingId: 'TRK-RED-9082',
      },
    ],
  },
  {
    id: 'CAM-AMS-02-THERMAL',
    cameraName: 'Centraal Station Metro North Gate Thermal-02',
    sector: 'SECTOR-1B-METRO',
    lat: 52.3788,
    lng: 4.8992,
    resolution: '1080p 120FPS (LWIR Thermal Matrix)',
    fps: 120,
    feedType: 'THERMAL_OPTICAL',
    activeTargets: [
      {
        subjectId: 'SUB-9082',
        subjectName: 'Elena V. Rostova',
        boundingBox: { x: 52, y: 30, width: 22, height: 40 },
        matchConfidence: 97.2,
        trackingId: 'TRK-RED-9082',
      },
    ],
  },
  {
    id: 'CAM-DAM-03-STREET',
    cameraName: 'Dam Square Pedestrian Matrix 360',
    sector: 'SECTOR-2A-PLAZA',
    lat: 52.3732,
    lng: 4.8926,
    resolution: '4K 60FPS Panoramic',
    fps: 60,
    feedType: 'SYNTHETIC_CCTV',
    activeTargets: [
      {
        subjectId: 'SUB-2104',
        subjectName: 'Lucas K. Vance',
        boundingBox: { x: 20, y: 40, width: 18, height: 35 },
        matchConfidence: 97.8,
        trackingId: 'TRK-BLU-2104',
      },
    ],
  },
];

export const INITIAL_MERKLE_BLOCKS: MerkleAuditBlock[] = [
  {
    blockHeight: 14082,
    hash: '0x3f98a72b01449cb88102394ac10928be8810cba48102893acbd92841029384bb',
    previousHash: '0x1a8842bc99104fa772019488bca819203948afc881029348102938491029384a',
    merkleRoot: '0x99201fba4410928be819234acb10928340192834bca81920394810293847192a',
    action: 'GEOFENCE_BREACH_ALERT_DISPATCHED',
    subjectDid: 'did:aegis:7f89d3a180429b61e29c',
    actorNodeId: 'NODE-RELAY-01-AMS',
    payloadSummary: 'Unauthorized departure into Rail Corridor 15B detected by Neural CCTV Cam 01',
    timestamp: new Date(Date.now() - 40000).toISOString(),
    signature: '0xed25519:8819024fba99102834acb10928340192834',
    status: 'VERIFIED_ON_CHAIN',
  },
  {
    blockHeight: 14081,
    hash: '0x1a8842bc99104fa772019488bca819203948afc881029348102938491029384a',
    previousHash: '0x7c81920349182304918230941823094812309481230948123094812093481203',
    merkleRoot: '0x4419203841029384acb10928340192834bca81920394810293847192a9918234',
    action: 'BANKCARD_POS_SWIPE_CROSS_REFERENCED',
    subjectDid: 'did:aegis:7f89d3a180429b61e29c',
    actorNodeId: 'NODE-RELAY-01-AMS',
    payloadSummary: 'Point of Sale transaction €148.50 at Rail Ticketing mapped to Biometric Sighting',
    timestamp: new Date(Date.now() - 95000).toISOString(),
    signature: '0xed25519:77102934acb10928340192834bca819203',
    status: 'VERIFIED_ON_CHAIN',
  },
  {
    blockHeight: 14080,
    hash: '0x7c81920349182304918230941823094812309481230948123094812093481203',
    previousHash: '0x5501928340192834019283401928340192834019283401928340192834019283',
    merkleRoot: '0x11029384acb10928340192834bca81920394810293847192a991823444192038',
    action: 'SOVEREIGN_DID_AUTH_KEY_ROTATED',
    subjectDid: 'did:aegis:e44b89110294fcda3108',
    actorNodeId: 'NODE-RELAY-04-RESEARCH',
    payloadSummary: 'Ed25519 Ephemeral Session Key rotated under zero-knowledge authorization',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    signature: '0xed25519:66102934acb10928340192834bca819203',
    status: 'VERIFIED_ON_CHAIN',
  },
];

export const INITIAL_SOVEREIGN_DIDS: SovereignDID[] = [
  {
    did: 'did:aegis:7f89d3a180429b61e29c',
    alias: 'Elena Rostova (Sovereign Citizen Keyring)',
    publicKeyHex: '0x04e19024fba99102834acb10928340192834bca81920394810293847192a9918',
    keyType: 'Ed25519',
    createdDate: '2025-11-14T08:22:10Z',
    isPrimary: true,
    credentialsCount: 4,
    seedPhrasePreview: 'sovereign beacon lattice cipher sentinel orbital ...',
    guardians: ['did:aegis:guardian-alpha-9', 'did:aegis:guardian-defense-vault'],
  },
  {
    did: 'did:aegis:e44b89110294fcda3108',
    alias: 'Dr. Tariq Al-Mansoor (Defense Clear L4)',
    publicKeyHex: '0x04bca81920394810293847192a99182344419203841029384acb109283401928',
    keyType: 'Ed25519',
    createdDate: '2026-01-09T14:15:30Z',
    isPrimary: false,
    credentialsCount: 6,
    seedPhrasePreview: 'quantum enclave titan zero proof apex vector ...',
    guardians: ['did:aegis:guardian-quantum-council'],
  },
];

export const INITIAL_CREDENTIALS: VerifiableCredential[] = [
  {
    id: 'VC-DEFENSE-88190',
    type: 'NationalDefenseClearanceCredential',
    issuerDid: 'did:aegis:gov-defense-agency',
    subjectDid: 'did:aegis:e44b89110294fcda3108',
    issuanceDate: '2026-01-10T00:00:00Z',
    expirationDate: '2027-01-10T00:00:00Z',
    claims: {
      clearanceLevel: 4,
      specialization: 'Quantum Lattice Cryptography',
      sovereignJurisdiction: 'EU-NATO-ALLIANCE',
      biometricVerified: true,
    },
    zkpProofAvailable: true,
    zkpPredicate: 'ClearanceLevel >= 3 (Revealing 0 raw credentials)',
    status: 'VALID',
    proofSignature: '0xed25519:998102384acb10928340192834bca819203',
  },
  {
    id: 'VC-CITIZEN-99014',
    type: 'SovereignDecentralizedPassport',
    issuerDid: 'did:aegis:gov-civil-registry',
    subjectDid: 'did:aegis:7f89d3a180429b61e29c',
    issuanceDate: '2025-06-01T00:00:00Z',
    expirationDate: '2030-06-01T00:00:00Z',
    claims: {
      citizenship: 'Netherlands',
      ageOver18: true,
      sovereignPrivacyOptIn: true,
      biometricTemplateHash: '0x9e88b22a0145cbf988941094038aee8c1',
    },
    zkpProofAvailable: true,
    zkpPredicate: 'Age >= 18 && ValidCitizenship (Zero knowledge)',
    status: 'VALID',
    proofSignature: '0xed25519:7741029384acb10928340192834bca819',
  },
];

export const INITIAL_ALERT_RULES: AutomatedAlertRule[] = [
  {
    id: 'RULE-01-GEOFENCE',
    name: 'Critical Asset Geofence Boundary Breach',
    condition: 'target.threatLevel >= HIGH && target.distanceFromPerimeter < 50m',
    severity: 'CRITICAL_CODE_RED',
    isActive: true,
    autoLockdown: true,
    notifyNodes: ['NODE-RELAY-01-AMS', 'NODE-RELAY-04-RESEARCH'],
    triggerCount: 3,
    lastTriggered: new Date(Date.now() - 45000).toISOString(),
  },
  {
    id: 'RULE-02-BIOMETRIC-ANOMALY',
    name: 'Watchlist Biometric & Iris Correlation Match >= 95%',
    condition: 'cctv.faceMatchScore >= 95.0% && govStatus == WATCHLIST_RED_NOTICE',
    severity: 'CRITICAL_CODE_RED',
    isActive: true,
    autoLockdown: true,
    notifyNodes: ['ALL_NODES'],
    triggerCount: 1,
    lastTriggered: new Date(Date.now() - 50000).toISOString(),
  },
  {
    id: 'RULE-03-TRANSIT-POS-CROSS',
    name: 'Rapid Transit Exit Cross-Referenced with Large Fiat POS/ATM',
    condition: 'transit.timeDelta(pos.time) < 5min && pos.amount >= €500',
    severity: 'HIGH',
    isActive: true,
    autoLockdown: false,
    notifyNodes: ['NODE-RELAY-01-AMS', 'NODE-RELAY-02-FINANCIAL'],
    triggerCount: 4,
    lastTriggered: new Date(Date.now() - 95000).toISOString(),
  },
  {
    id: 'RULE-04-TELEMETRY-DRIFT',
    name: 'Sensor Mesh Latency Drift & Route Divergence Watch',
    condition: 'node.latencyVariance > 35ms || transit.routeDivergence == true',
    severity: 'ELEVATED',
    isActive: true,
    autoLockdown: false,
    notifyNodes: ['NODE-RELAY-02-FINANCIAL', 'NODE-RELAY-03-AMS'],
    triggerCount: 3,
    lastTriggered: new Date(Date.now() - 110000).toISOString(),
  },
];

export const INITIAL_ACTIVE_ALERTS: ActiveAlertLog[] = [
  {
    id: 'ALT-88401',
    ruleId: 'RULE-01-GEOFENCE',
    title: 'GEOFENCE BOUNDARY BREACH - SECTOR 1A RAIL CORRIDOR',
    subjectName: 'Elena V. Rostova (CIPHER_NIGHTINGALE)',
    subjectId: 'SUB-9082',
    severity: 'CRITICAL_CODE_RED',
    priorityLevel: 'CRITICAL',
    timestamp: new Date(Date.now() - 45000).toISOString(),
    locationDetails: 'Platform 15B High Speed Rail Gate (Lat 52.379189, Lng 4.899431)',
    details: 'Target entered international high-speed boarding zone after flagged ATM withdrawal and metro exit.',
    actionTaken: 'Autonomous node alert dispatched to orbital radar; CCTV lock engaged; gate telemetry locked.',
    isResolved: false,
  },
  {
    id: 'ALT-88400',
    ruleId: 'RULE-02-BIOMETRIC-ANOMALY',
    title: 'RED NOTICE BIOMETRIC VECTOR POSITIVE (99.4% MATCH)',
    subjectName: 'Elena V. Rostova',
    subjectId: 'SUB-9082',
    severity: 'CRITICAL_CODE_RED',
    priorityLevel: 'CRITICAL',
    timestamp: new Date(Date.now() - 50000).toISOString(),
    locationDetails: 'Metro 52 Noord-Zuidlijn Turnstile 04B',
    details: 'Optical CCTV face vector scored 99.4% match with Interpol Red Notice Registry 2026-9921.',
    actionTaken: 'Biometric packet signed and broadcasted across all encrypted node relays.',
    isResolved: false,
  },
  {
    id: 'ALT-88395',
    ruleId: 'RULE-03-TRANSIT-POS-CROSS',
    title: 'TRANSIT & POS CORRELATION ADVISORY // ROUTE DIVERGENCE',
    subjectName: 'Dr. Aris Vance (ZERO_TRACE)',
    subjectId: 'SUB-4410',
    severity: 'ELEVATED',
    priorityLevel: 'ADVISORY',
    timestamp: new Date(Date.now() - 95000).toISOString(),
    locationDetails: 'Nieuwmarkt Station Node Relay (Sector 2 - Lat 52.37180, Lng 4.90110)',
    details: 'Contactless high-frequency micropayment correlated with sudden transit reroute. Perimeter intact; telemetry flag raised for passive tracking.',
    actionTaken: 'Secondary optical node directed to log pass-through vector; continuous mesh heartbeat maintained.',
    isResolved: false,
  },
  {
    id: 'ALT-88390',
    ruleId: 'RULE-04-TELEMETRY-DRIFT',
    title: 'TELEMETRY MESH LATENCY ADVISORY // SENSOR JITTER',
    subjectName: 'Marcus "Ghost" Chen',
    subjectId: 'SUB-1029',
    severity: 'GUARDED',
    priorityLevel: 'ADVISORY',
    timestamp: new Date(Date.now() - 140000).toISOString(),
    locationDetails: 'Oosterdok Quantum Relay Node #03 (Sector 3 - Lat 52.37520, Lng 4.91240)',
    details: 'Beacon ping latency variance exceeded +45ms threshold. Auxiliary CCTV camera array maintaining positive optical correlation.',
    actionTaken: 'Relay packet rerouted to backup encrypted line; advisory status flagged for operator review.',
    isResolved: false,
  },
];

export const POLICE_STATIONS: PoliceStation[] = [
  {
    id: 'STATION-01-CENTRAAL-SPOORWEG',
    name: 'Spoorwegpolitie & Marechaussee Rapid Tactical Unit',
    callsign: 'KMAR-CENTRAAL-ALPHA',
    jurisdiction: 'Koninklijke Marechaussee & Spoorwegpolitie',
    address: 'Stationsplein 15, 1012 AB Amsterdam (Centraal Hub)',
    lat: 52.37912,
    lng: 4.90025,
    radioFrequency: 'TETRA C2000 CH-401 (380.125 MHz)',
    cadTerminalCode: 'CAD-AMS-CENTRAAL-01',
    status: 'CODE_RED_ALERT',
    availableUnits: 6,
    unitTypes: [
      'Tactical Rapid Intercept (K-MAR)',
      'Platform Perimeter Cordon Unit',
      'Canine Explosive/Tracking K9',
      'High-Speed Turnstile Intercept',
    ],
    telephoneEmergency: '+31 20 531 3400 / 112 DIRECT',
    directTetraChannel: 'TETRA-SEC-GROUP-991',
  },
  {
    id: 'STATION-02-NIEUWEZIJDS',
    name: 'Politiebureau Nieuwezijds Voorburgwal (Central Precinct)',
    callsign: 'POLITIE-AMS-ECHO-12',
    jurisdiction: 'Nationale Politie Eenheid Amsterdam (Sector Centrum)',
    address: 'Nieuwezijds Voorburgwal 104, 1012 SG Amsterdam',
    lat: 52.37385,
    lng: 4.89122,
    radioFrequency: 'TETRA C2000 CH-402 (380.250 MHz)',
    cadTerminalCode: 'CAD-AMS-CENTRUM-12',
    status: 'ONLINE_DISPATCH_READY',
    availableUnits: 8,
    unitTypes: [
      'Sector Patrol Cruisers (4x Units)',
      'Motorcycle Fast Response (2x Units)',
      'Undercover Surveillance Intercept',
      'Drone Aerial Support Sentry',
    ],
    telephoneEmergency: '+31 900 8844 / CAD 112',
    directTetraChannel: 'TETRA-SEC-GROUP-402',
  },
  {
    id: 'STATION-03-EUROPOL-MARITIME',
    name: 'Europol & Maritime River Police Intercept Post',
    callsign: 'EUROPOL-TASKFORCE-07',
    jurisdiction: 'Europol High Threat Directorate & Waterpolitie',
    address: 'De Ruijterkade Pier 10, 1011 AA Amsterdam',
    lat: 52.38095,
    lng: 4.9048,
    radioFrequency: 'EUROPOL SECURE WAN P25 (410.500 MHz)',
    cadTerminalCode: 'CAD-EUR-CROSSBORDER-99',
    status: 'ONLINE_DISPATCH_READY',
    availableUnits: 4,
    unitTypes: [
      'Maritime High-Speed Intercept RIB',
      'International Fugitive Taskforce',
      'Electronic Countermeasures Van',
    ],
    telephoneEmergency: '+31 70 302 5000',
    directTetraChannel: 'EUROPOL-DIRECT-ENCLAVE',
  },
  {
    id: 'STATION-04-LINNAEUSSTRAAT',
    name: 'Politiebureau Linnaeusstraat (East Sector Command)',
    callsign: 'POLITIE-AMS-FOXTROT-04',
    jurisdiction: 'Nationale Politie Eenheid Amsterdam (Sector Oost)',
    address: 'Linnaeusstraat 221, 1093 EP Amsterdam',
    lat: 52.3582,
    lng: 4.9275,
    radioFrequency: 'TETRA C2000 CH-405 (380.625 MHz)',
    cadTerminalCode: 'CAD-AMS-OOST-04',
    status: 'STANDBY',
    availableUnits: 5,
    unitTypes: [
      'Armed Response Unit (DSI Reserve)',
      'Sector Transit Support',
      'Mobile Forensic Command',
    ],
    telephoneEmergency: '+31 900 8844',
    directTetraChannel: 'TETRA-SEC-GROUP-405',
  },
];

export const INITIAL_DISPATCH_HISTORY: ThreatDispatchPacket[] = [
  {
    dispatchId: 'CAD-DISP-2026-99014',
    targetStationId: 'STATION-01-CENTRAAL-SPOORWEG',
    targetStationName: 'Spoorwegpolitie & Marechaussee Rapid Tactical Unit',
    targetStationCallsign: 'KMAR-CENTRAAL-ALPHA',
    channel: 'TETRA_C2000_POLICE_NET',
    priority: 'PRIORITY_1_CODE_RED',
    subjectId: 'SUB-9082',
    subjectName: 'Elena V. Rostova',
    subjectAlias: 'CIPHER_NIGHTINGALE',
    subjectDid: 'did:aegis:7f89d3a180429b61e29c',
    nationalId: 'NL-8842-99120-A',
    threatLevel: 'CRITICAL_CODE_RED',
    incidentLocation: {
      lat: 52.379189,
      lng: 4.899431,
      altitudeMeters: 14.2,
      accuracyMeters: 1.8,
      headingDegrees: 142,
      speedKmh: 48.5,
      locationName: 'Platform 15B High Speed Rail Gate',
      zoneId: 'ZONE_HIGH_SECURITY_ALPHA',
      timestamp: new Date(Date.now() - 40000).toISOString(),
    },
    biometricMatchScore: 99.4,
    cctvSector: 'CCTV-CAM-01-PLATFORM15',
    tacticalRadioTranscript: 'ATTENTION ALL UNITS: PRIORITY 1 DISPATCH. SUBJECT ELENA ROSTOVA (RED NOTICE 2026-9921) SIGHTED AT PLATFORM 15B. HIGH CONFIDENCE 99.4% OPTICAL MATCH. ATTEMPTING BOARDING THALYS 9328. ENGAGE TURNSTILE LOCKDOWN AND DEPLOY CORDON.',
    containmentDirectives: [
      'Immediate turnstile barrier electromagnetic lock at Platform 15B',
      'Deploy 2x K-MAR tactical officers to gate corridor',
      'Activate high-definition PTZ optical tracking from Cam 01',
      'Seal international departure vestibule',
    ],
    authorizedOfficerDid: 'did:aegis:commander-vault-01',
    timestamp: new Date(Date.now() - 40000).toISOString(),
    status: 'UNITS_DISPATCHED',
    acknowledgedByOfficerCallsign: 'DISPATCHER-HAGUE-CAD-44',
    sha256Seal: '0x88921aae09183ba41908234eaac90182390412893810293847a1029384102938',
    estimatedResponseTimeSeconds: 45,
    assignedPatrolUnits: ['KMAR-PATROL-04', 'KMAR-K9-SENTRY'],
  },
];

export const MOST_WANTED_LIST: MostWantedFugitive[] = [
  // =================== FBI TOP 10 MOST WANTED ===================
  {
    id: 'FUG-FBI-01',
    agency: 'FBI',
    noticeType: 'FBI_TOP_TEN',
    fullName: 'Ruja Ignatova',
    alias: 'THE_CRYPTOQUEEN',
    aliases: ['Ruja Plamenova Ignatova', 'Dr. Ruja', 'Elena Petrova', 'Wanda Brandt'],
    bountyReward: '$5,000,000 USD',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'EXTREME',
    fbiCaseId: 'FBI-NY-2017-ONECOIN-01',
    charges: [
      'Conspiracy to Commit Wire Fraud',
      'Wire Fraud',
      'Conspiracy to Commit Money Laundering',
      'Conspiracy to Commit Securities Fraud',
      'Securities Fraud ($4.5B Global Defraudation)',
    ],
    syndicate: 'OneCoin Transnational Ponzi & Sovereign Money Laundering Network',
    summary:
      'Founder of OneCoin pyramid fraud scheme. Traveled from Sofia to Athens in 2017 and vanished. Known to travel with armed guards and may have altered appearance through plastic surgery or fraudulent sovereign passports.',
    nationality: 'Bulgarian / German',
    age: 44,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 37.9838,
      lng: 23.7275,
      city: 'Athens / Mediterranean Maritime Corridor',
      country: 'Greece / International Waters',
      sectorNote: 'Reported luxury yacht movement between Aegean & Black Sea ports under Maltese flag',
    },
    physicalDescription: {
      height: "5'6\" (168 cm)",
      weight: '140 lbs (63 kg)',
      eyes: 'Brown (often wears cosmetic contact lenses)',
      hair: 'Dark Brown / Black (frequently dyed blonde or auburn)',
      scarsAndMarks: ['Extensive facial plastic surgery', 'Lip enhancement scars', 'Mole removed from right jaw'],
      cautionNotes: 'Subject is considered armed and dangerous. Travels with former Eastern European state security operators.',
    },
    biometrics: {
      irisHash: '0x99a812bf09e248b19a0021c4fa9910b83e449281a9c481902847a1',
      faceMatchScore: 94.8,
      dnaMarkerReference: 'DNA-REF-BUL-2017-991',
      voiceprintHarmonicScore: 89.2,
    },
    associatedWeaponry: ['Glock 19 Gen 5', 'Private Armed Detail with MP5 Submachine Guns'],
  },
  {
    id: 'FUG-FBI-02',
    agency: 'FBI',
    noticeType: 'FBI_TOP_TEN',
    fullName: 'Yulan Adonay Archaga Carias',
    alias: 'PORKY',
    aliases: ['Alexander Mendoza', 'Porky Archaga', 'El Jefe de Jefes'],
    bountyReward: '$5,000,000 USD',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'EXTREME',
    fbiCaseId: 'FBI-SDNY-2021-MS13-44',
    charges: [
      'Conspiracy to Violate the Racketeer Influenced and Corrupt Organizations Act (RICO)',
      'Conspiracy to Import Cocaine into the United States',
      'Conspiracy to Possess Machine Guns in Furtherance of Drug Trafficking',
      'Murder in Aid of Racketeering',
    ],
    syndicate: 'Mara Salvatrucha (MS-13) Supreme National Council',
    summary:
      'Highest-ranking leader of MS-13 in Honduras. Orchestrated multi-ton cocaine shipments, contract assassinations, and illicit firearm distribution across North America. Escaped from custody in El Progreso during a violent commando raid in 2020.',
    nationality: 'Honduran',
    age: 42,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 15.5042,
      lng: -88.025,
      city: 'San Pedro Sula / Central American Transit Grid',
      country: 'Honduras / Guatemala Border',
      sectorNote: 'Protected by armed paramilitaries with military-grade rifles and encrypted radios',
    },
    physicalDescription: {
      height: "5'5\" (165 cm)",
      weight: '160 lbs (72 kg)',
      eyes: 'Brown',
      hair: 'Black / Shaved',
      scarsAndMarks: ['Extensive MS-13 tattoos on chest, back, and left arm', 'Scar across right forearm'],
      cautionNotes: 'Extremely violent. Subject has commanded hits on law enforcement and judicial officers.',
    },
    biometrics: {
      irisHash: '0x19284ba01928374a91823bc0192847a9182bc09182734610293847',
      faceMatchScore: 96.1,
      dnaMarkerReference: 'DNA-REF-HON-2020-MS13',
      voiceprintHarmonicScore: 91.5,
    },
    associatedWeaponry: ['AK-47 Tactical', 'M4 Carbines', 'Fragmentation Grenades'],
  },
  {
    id: 'FUG-FBI-03',
    agency: 'FBI',
    noticeType: 'FBI_TOP_TEN',
    fullName: 'Bhadreshkumar Chetanbhai Patel',
    alias: 'BHADRESH_PATEL',
    aliases: ['Bhadresh Patel', 'Chetan Patel'],
    bountyReward: '$250,000 USD',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'HIGH',
    fbiCaseId: 'FBI-BALT-2015-PATEL-99',
    charges: [
      'First Degree Murder',
      'Second Degree Murder',
      'First Degree Assault',
      'Second Degree Assault',
      'Unlawful Flight to Avoid Prosecution',
    ],
    syndicate: 'Individual Federal Fugitive / Transnational Flight',
    summary:
      'Wanted for stabbing his wife to death in a commercial bakery in Hanover, Maryland in 2015. Patel took a cab to Newark Airport and is believed to have fled abroad or secured false sovereign identification documents.',
    nationality: 'Indian',
    age: 34,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 40.6895,
      lng: -74.1745,
      city: 'Newark / Global Transit Hub',
      country: 'United States / Transnational Exit',
      sectorNote: 'Last confirmed sighting at Newark Penn Station booking transit under alias',
    },
    physicalDescription: {
      height: "5'9\" (175 cm)",
      weight: '165 lbs (75 kg)',
      eyes: 'Brown',
      hair: 'Brown / Black',
      scarsAndMarks: ['Mole below left eye', 'Piercing scar in left earlobe'],
      cautionNotes: 'Should be considered armed, dangerous, and an extreme international flight risk.',
    },
    biometrics: {
      irisHash: '0x884920192847a0192847b0192847c0192847d0192847e0192847f0',
      faceMatchScore: 92.4,
      dnaMarkerReference: 'DNA-REF-USA-2015-PATEL',
      voiceprintHarmonicScore: 84.7,
    },
    associatedWeaponry: ['Concealed Blade', 'Illegal Handgun'],
  },
  {
    id: 'FUG-FBI-04',
    agency: 'FBI',
    noticeType: 'FBI_TOP_TEN',
    fullName: 'Alejandro Rosales Castillo',
    alias: 'ALEX_CASTILLO',
    aliases: ['Alexandro Castillo', 'Alejandro Castillo'],
    bountyReward: '$250,000 USD',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'HIGH',
    fbiCaseId: 'FBI-CHAR-2016-CASTILLO',
    charges: [
      'First Degree Murder',
      'Armed Robbery',
      'Unlawful Flight to Avoid Prosecution',
      'Federal Interstate Flight',
    ],
    syndicate: 'Criminal Armed Robbery & Fugitive Cell',
    summary:
      'Wanted in connection with the August 2016 armed murder of a co-worker in Charlotte, North Carolina. Castillo fled with a co-defendant, driving through South Carolina into Mexico through Nogales, Arizona.',
    nationality: 'American / Mexican',
    age: 26,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 20.6597,
      lng: -103.3496,
      city: 'Guadalajara / Jalisco Corridor',
      country: 'Mexico',
      sectorNote: 'Reported operating in western Mexico with forged commercial transport credentials',
    },
    physicalDescription: {
      height: "5'6\" (168 cm)",
      weight: '180 lbs (82 kg)',
      eyes: 'Brown',
      hair: 'Black',
      scarsAndMarks: ['Tattoo of skull on left forearm', 'Burn mark on right shoulder'],
      cautionNotes: 'Subject possesses firearms and has demonstrated willingness to use lethal force.',
    },
    biometrics: {
      irisHash: '0x334455667788990011223344556677889900aabbccddeeff001122',
      faceMatchScore: 93.9,
      dnaMarkerReference: 'DNA-REF-NC-2016-CASTILLO',
      voiceprintHarmonicScore: 86.3,
    },
    associatedWeaponry: ['9mm Semi-Automatic Pistol'],
  },

  // =================== INTERPOL RED NOTICES ===================
  {
    id: 'FUG-INTERPOL-01',
    agency: 'INTERPOL',
    noticeType: 'INTERPOL_RED_NOTICE',
    fullName: 'Elena V. Rostova',
    alias: 'CIPHER_NIGHTINGALE',
    aliases: ['Elena Volkova', 'Alina Rostova', 'Dr. E. Richter', 'Cipher Zero'],
    bountyReward: '€2,000,000 EUR',
    status: 'TRACKED_IN_SECTOR',
    dangerRating: 'CRITICAL',
    interpolNoticeNumber: 'INTERPOL-A-3312/26-NL',
    charges: [
      'High-Yield Critical Infrastructure Cyber-Extortion',
      'Quantum Key Distribution (QKD) Wiretapping',
      'Transnational Cryptographic Asset Laundering',
      'Schengen Border Evasion & Counterfeit Sovereign Identity Generation',
    ],
    syndicate: 'Ghost Citadel Transnational Cyber Cartel / Sovereign Infiltration Node',
    summary:
      'Subject is currently flagged in God\'s Eye Amsterdam Sector 1A attempting high-speed international transit departure. Wanted across 7 EU member states and INTERPOL Lyon HQ for orchestrating deep telemetry taps and bankcard token intercept syndicates.',
    nationality: 'Russian / Dutch (Disputed Sovereign DID)',
    age: 33,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face',
    correlatedTrackedSubjectId: 'SUB-9082',
    lastKnownLocation: {
      lat: 52.379189,
      lng: 4.899431,
      city: 'Amsterdam Centraal Station / Platform 15B',
      country: 'Netherlands',
      sectorNote: 'LIVE INTERCEPT IN PROGRESS: Attempting Eurostar boarding to Brussels',
    },
    physicalDescription: {
      height: "5'8\" (173 cm)",
      weight: '128 lbs (58 kg)',
      eyes: 'Emerald Green',
      hair: 'Dark Brunette / Styled Short',
      scarsAndMarks: ['Micro-surgical incision behind right ear (neural telemetry port)', 'Geometrical tattoo on inner left wrist'],
      cautionNotes: 'Carries active zero-day EMP scrambling hardware and encrypted satellite transmitter.',
    },
    biometrics: {
      irisHash: '0x7f89d3a180429b61e29c0192847a91823bc09182734610293847',
      faceMatchScore: 99.4,
      dnaMarkerReference: 'DNA-REF-NL-2026-CIPHER',
      voiceprintHarmonicScore: 98.2,
    },
    associatedWeaponry: ['Signal Jamming EMP Emitter', 'Ceramic Blade'],
  },
  {
    id: 'FUG-INTERPOL-02',
    agency: 'INTERPOL',
    noticeType: 'INTERPOL_RED_NOTICE',
    fullName: 'Giovanni Motisi',
    alias: 'U_PACCHIUNI',
    aliases: ['Giovanni Motisi', 'The Fat One', 'Zio Gianni'],
    bountyReward: '€1,500,000 EUR',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'EXTREME',
    interpolNoticeNumber: 'INTERPOL-A-1029/98-IT',
    charges: [
      'Mafia Association (Cosa Nostra Supreme Leadership)',
      'Multiple First Degree Murders with Explosive Devices',
      'Mass Destruction & Anti-State Terrorist Bombings',
      'Extortion & Arms Trafficking Across the Mediterranean',
    ],
    syndicate: 'Cosa Nostra - Mandamento di Pagliarelli (Palermo)',
    summary:
      'Historical supreme boss of the Pagliarelli mafia clan in Palermo. Close associate of Totò Riina and Bernardo Provenzano. Wanted since 1998 for assassinating police officials and executing car bombing campaigns in Capaci and Florence.',
    nationality: 'Italian',
    age: 67,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 38.1157,
      lng: 13.3615,
      city: 'Palermo / Rural Sicilian Underground Network',
      country: 'Italy / French Riviera Transit',
      sectorNote: 'Sheltered by deep omertà network with fortified underground bunker residences',
    },
    physicalDescription: {
      height: "5'10\" (178 cm)",
      weight: '230 lbs (104 kg)',
      eyes: 'Dark Brown',
      hair: 'Grey / Receding',
      scarsAndMarks: ['Surgical scar on abdominal wall', 'Scar across bridge of nose'],
      cautionNotes: 'Always surrounded by armed bodyguards. High probability of booby-trapped safehouses.',
    },
    biometrics: {
      irisHash: '0x99182736451029384756a1b2c3d4e5f60718293847561029384756',
      faceMatchScore: 91.2,
      dnaMarkerReference: 'DNA-REF-ITA-1998-MOTISI',
      voiceprintHarmonicScore: 82.0,
    },
    associatedWeaponry: ['Beretta 92FS', 'C4 Explosive Detonators', 'Franchi SPAS-12'],
  },
  {
    id: 'FUG-INTERPOL-03',
    agency: 'INTERPOL',
    noticeType: 'INTERPOL_RED_NOTICE',
    fullName: 'Tiberiu Florescu',
    alias: 'BLACK_PHANTOM',
    aliases: ['Tiberiu F.', 'Phantom_Zero', 'GhostRoot_Admin', 'Radu Ionescu'],
    bountyReward: '€3,000,000 EUR',
    status: 'AT_LARGE',
    dangerRating: 'CRITICAL',
    interpolNoticeNumber: 'INTERPOL-A-4482/22-RO',
    charges: [
      'Transnational Ransomware Extortion ($350M Hospital Grid Attacks)',
      'Critical Energy Infrastructure Sabotage',
      'Darknet Automated Escrow Money Laundering',
      'Identity Theft of EU Citizens via Compromised Smart Meter Nodes',
    ],
    syndicate: 'LockBit Core Affiliate / DarkCrypt Collective',
    summary:
      'Chief architect of high-impact double-extortion ransomware strains targeting European healthcare centers and energy grids. Specializes in custom kernel rootkits and automated sovereign coin mixers.',
    nationality: 'Romanian / Moldovan',
    age: 38,
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 44.4268,
      lng: 26.1025,
      city: 'Bucharest / Black Sea Coastal Relay',
      country: 'Romania / Georgia Transit Corridor',
      sectorNote: 'Utilizes high-speed mobile satellite uplinks from moving armored transport',
    },
    physicalDescription: {
      height: "6'0\" (183 cm)",
      weight: '175 lbs (79 kg)',
      eyes: 'Blue / Grey',
      hair: 'Sandy Blonde',
      scarsAndMarks: ['Burn scar on left wrist from soldering iron', 'Glasses with anti-facial-scan infrared LEDs'],
      cautionNotes: 'Equipped with cryptographic dead-man switches configured to wipe server clusters upon capture.',
    },
    biometrics: {
      irisHash: '0x445566778899aabbccddeeff00112233445566778899aabbccddee',
      faceMatchScore: 95.7,
      dnaMarkerReference: 'DNA-REF-ROU-2022-FLORESCU',
      voiceprintHarmonicScore: 94.1,
    },
    associatedWeaponry: ['Stun Device', 'Thermal Grenade for Hardware Destruction'],
  },
  {
    id: 'FUG-INTERPOL-04',
    agency: 'INTERPOL',
    noticeType: 'INTERPOL_RED_NOTICE',
    fullName: 'Amir Reza Soltani',
    alias: 'THE_PERSIAN_CORSAIR',
    aliases: ['Captain Soltani', 'Reza Hosseini', 'Farid Al-Najjar'],
    bountyReward: '$3,500,000 USD',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'EXTREME',
    interpolNoticeNumber: 'INTERPOL-A-9011/24-IR',
    charges: [
      'Transnational High-Seas Narcotics Smuggling (Multi-Ton Cocaine/Methamphetamine)',
      'Unlawful Anti-Ship Munitions & Drone Part Smuggling',
      'Port Logistics Cyber-Infiltration (Rotterdam, Antwerp, Valencia)',
      'Maritime Piracy & Vessel Hijacking in Gulf of Oman',
    ],
    syndicate: 'Trans-Eurasian Maritime Smuggling Syndicate / Red Sea Shadow Fleet',
    summary:
      'Coordinates deep-sea mother-ship offloading and automated semi-submersible narco-drones across the Mediterranean and North Sea. Known to subvert container terminal crane operating systems to extract illicit cargo.',
    nationality: 'Iranian / Panamanian Flag of Convenience',
    age: 51,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 51.9244,
      lng: 4.4777,
      city: 'Port of Rotterdam / Europort Terminal',
      country: 'Netherlands / Maritime Sector',
      sectorNote: 'Reported inspecting container freight terminals near Maasvlakte Deepwater Berth',
    },
    physicalDescription: {
      height: "5'11\" (180 cm)",
      weight: '195 lbs (88 kg)',
      eyes: 'Dark Brown',
      hair: 'Salt and Pepper / Full Beard',
      scarsAndMarks: ['Anchor tattoo on right bicep', 'Bullet graze scar on left collarbone'],
      cautionNotes: 'Operates with armed paramilitary crew on ocean-going tugs and cargo ships.',
    },
    biometrics: {
      irisHash: '0x1234567890abcdef1234567890abcdef1234567890abcdef123456',
      faceMatchScore: 93.3,
      dnaMarkerReference: 'DNA-REF-MAR-2024-SOLTANI',
      voiceprintHarmonicScore: 87.9,
    },
    associatedWeaponry: ['RPK Light Machine Gun', 'Zastava M70', 'Scorpion EVO 3'],
  },

  // =================== MI6 / SIS SECRET INTELLIGENCE SERVICE ===================
  {
    id: 'FUG-MI6-01',
    agency: 'MI6',
    noticeType: 'MI6_SIS_ALPHA',
    fullName: 'Dmitry "Specter" Kozlov',
    alias: 'SPECTER_ZERO',
    aliases: ['Col. Dmitry Kozlov', 'Viktor Orlov', 'Sergei Morozov', 'Specter Prime'],
    bountyReward: '£2,500,000 GBP',
    status: 'IMMEDIATE_INTERCEPT',
    dangerRating: 'EXTREME',
    mi6Reference: 'SIS-DIR-ALPHA-09',
    charges: [
      'High Treason & Hostile Intelligence Sabotage Against Allied Critical Networks',
      'Subsea Telecommunications Fiber-Optic Cable Tap & EMP Intercept',
      'Assassination of Defected Sovereign Cryptographers in London & Geneva',
      'Deployment of Chemical-Precursor Weaponry in Western Urban Sectors',
    ],
    syndicate: 'Unit 29155 / Sandworm Special Reconnaissance Directorate',
    summary:
      'Disavowed former state intelligence directorate operator specializing in underwater infrastructure demolition and quantum decryption key theft. Primary suspect in the Thames fiber cut and Zurich embassy dead-drop assassinations.',
    nationality: 'Russian / Dual Cypriot Golden Passport (Revoked)',
    age: 49,
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 51.5074,
      lng: -0.1278,
      city: 'London / Canary Wharf Financial Core',
      country: 'United Kingdom / English Channel Transit',
      sectorNote: 'Tracked utilizing diplomatic frequency cloakers near Vauxhall Cross',
    },
    physicalDescription: {
      height: "6'2\" (188 cm)",
      weight: '210 lbs (95 kg)',
      eyes: 'Steel Grey',
      hair: 'Buzzcut Grey / Receding',
      scarsAndMarks: ['Severe shrapnel scar along right side of ribcage', 'Prosthetic left pinky finger'],
      cautionNotes: 'Expert in Krav Maga, Sambo, and evasive surveillance counter-measures. Lethal at all ranges.',
    },
    biometrics: {
      irisHash: '0xfeedfacefeedfacefeedfacefeedfacefeedfacefeedfacefeedface',
      faceMatchScore: 97.5,
      dnaMarkerReference: 'DNA-REF-SIS-2026-SPECTER',
      voiceprintHarmonicScore: 96.0,
    },
    associatedWeaponry: ['Makarov PB Silenced', 'Sub-aquatic Demolition Charges', 'VSS Vintorez Sniper'],
  },
  {
    id: 'FUG-MI6-02',
    agency: 'MI6',
    noticeType: 'MI6_SIS_ALPHA',
    fullName: 'Marcus "Vane" Sterling',
    alias: 'WARLORD_VANE',
    aliases: ['Major Sterling (Ret.)', 'Marcus Vance', 'Vane Tactical', 'Galahad Black'],
    bountyReward: '£1,750,000 GBP',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'EXTREME',
    mi6Reference: 'SIS-EX-MIL-882',
    charges: [
      'Unlawful Brokering of MANPADS & Anti-Armor Missile Systems',
      'Breach of the Official Secrets Act & Tactical Radio Encryption Theft',
      'Private Military Coup Orchestration in Sub-Saharan Lithium Belts',
      'Murder of Crown Observers & Diplomatic Escorts in Mogadishu',
    ],
    syndicate: 'Obsidian Tactical PMC / Disavowed Black Water Recon Group',
    summary:
      'Former British Special Boat Service (SBS) operative turned rogue private military contractor. Commands a 120-man mercenary force armed with illicit high-grade NATO weaponry and encrypted tactical mesh gear.',
    nationality: 'British / South African',
    age: 46,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 43.7384,
      lng: 7.4246,
      city: 'Monaco / Heliport Mediterranean Hub',
      country: 'Monaco / French Riviera Transit',
      sectorNote: 'Boarding private rotorcraft with false maritime defense accreditation',
    },
    physicalDescription: {
      height: "6'1\" (185 cm)",
      weight: '200 lbs (91 kg)',
      eyes: 'Hazel',
      hair: 'Brown / Spiked',
      scarsAndMarks: ['SBS dagger tattoo on inner right forearm', 'Shrapnel burn on left cheek'],
      cautionNotes: 'Assumed to possess thermal optical sights and armored body armor rating Level IV.',
    },
    biometrics: {
      irisHash: '0x99887766554433221100ffeeddccbbaa99887766554433221100',
      faceMatchScore: 98.1,
      dnaMarkerReference: 'DNA-REF-SIS-1999-STERLING',
      voiceprintHarmonicScore: 92.8,
    },
    associatedWeaponry: ['Sig Sauer MCX Spear (.277 Fury)', 'Glock 17T', 'AN/PVS-31 Night Vision'],
  },
  {
    id: 'FUG-MI6-03',
    agency: 'MI6',
    noticeType: 'MI6_SIS_ALPHA',
    fullName: 'Amina Al-Mansoor',
    alias: 'THE_SOVEREIGN_ALCHEMIST',
    aliases: ['Princess Amina', 'Amina Sterling', 'Layla Al-Khatib', 'Oracle_Vault'],
    bountyReward: '£2,000,000 GBP',
    status: 'AT_LARGE',
    dangerRating: 'HIGH',
    mi6Reference: 'SIS-FIN-SHADOW-401',
    charges: [
      'Multi-Billion Sovereign Sanctions Evasion & Illicit WMD Escrow Funding',
      'Darkpool Decentralized Exchange Front-Running & Liquidity Laundering',
      'Financing of Covert Kinetic Sabotage Cells in Western European Capital Hubs',
      'Bribery and Extortion of Sovereign Central Bank Board Members',
    ],
    syndicate: 'Al-Mansoor Shadow Capital Syndicate / Sovereign Trust Cayman',
    summary:
      'Oxford-educated sovereign wealth strategist who controls over $8 billion in un-traceable bearer bonds, tokenized gold reserves, and darkpool liquidity vaults used to fund rogue intelligence and mercenary operations worldwide.',
    nationality: 'Emirati / British Dual Citizen',
    age: 39,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 47.3769,
      lng: 8.5417,
      city: 'Zurich / Bahnhofstrasse Private Banking Vaults',
      country: 'Switzerland / Geneva Private Jet Terminal',
      sectorNote: 'Accessing underground gold depository under diplomatic courier immunity',
    },
    physicalDescription: {
      height: "5'7\" (170 cm)",
      weight: '132 lbs (60 kg)',
      eyes: 'Dark Amber',
      hair: 'Glossy Black / Wavy',
      scarsAndMarks: ['Gold crescent pendant containing hardware private key', 'Faint scar on left temple'],
      cautionNotes: 'Protected by Swiss-trained close protection officers with diplomatic pouch immunity.',
    },
    biometrics: {
      irisHash: '0x00112233445566778899aabbccddeeff00112233445566778899',
      faceMatchScore: 96.8,
      dnaMarkerReference: 'DNA-REF-SIS-2024-ALMANSOOR',
      voiceprintHarmonicScore: 95.4,
    },
    associatedWeaponry: ['Diplomatic Armed Escorts (SIG Sauer P320)'],
  },

  // =================== EUROPOL MOST WANTED ===================
  {
    id: 'FUG-EUROPOL-01',
    agency: 'EUROPOL',
    noticeType: 'EUROPOL_MOST_WANTED',
    fullName: 'Jos Leijdekkers',
    alias: 'BOLLE_JOS',
    aliases: ['Bolle Jos', 'Jos L.', 'El Gordito', 'Mocro Nexus Chief'],
    bountyReward: '€200,000 EUR',
    status: 'ARMED_AND_DANGEROUS',
    dangerRating: 'EXTREME',
    europolRef: 'EUROPOL-NL-2022-LEIJ',
    charges: [
      'Large-Scale Transnational Cocaine Smuggling via Rotterdam & Antwerp Ports',
      'Laundering of Tens of Millions in Gold Bullion and Cryptographic Tokens',
      'Kidnapping, Torture, and Disappearance of Naima Jillal',
      'High-Level Violence and Retaliation Against Witnesses and Customs Officials',
    ],
    syndicate: 'Mocro Maffia Supreme Cartel / Super Cartel Dubai Alliance',
    summary:
      'One of the principal key figures in the large-scale international cocaine trade in Europe. Wanted by the Dutch National Police and Europol. Suspected of living in Dubai or Turkey with false papers and armed security.',
    nationality: 'Dutch',
    age: 33,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face',
    lastKnownLocation: {
      lat: 25.2048,
      lng: 55.2708,
      city: 'Dubai / Palm Jumeirah Ultra-Luxury Compound',
      country: 'United Arab Emirates / Turkey Transit',
      sectorNote: 'Utilizes multiple encrypted satellite phones and private maritime charters',
    },
    physicalDescription: {
      height: "5'10\" (178 cm)",
      weight: '215 lbs (98 kg)',
      eyes: 'Blue / Grey',
      hair: 'Short Brown / Stubble',
      scarsAndMarks: ['Stout build', 'Scar above right eyebrow'],
      cautionNotes: 'Extremely dangerous. Employs contract killers armed with automatic weaponry.',
    },
    biometrics: {
      irisHash: '0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef',
      faceMatchScore: 94.2,
      dnaMarkerReference: 'DNA-REF-NL-2022-LEIJDEKKERS',
      voiceprintHarmonicScore: 88.6,
    },
    associatedWeaponry: ['Desert Eagle .50 AE', 'Scorpion Submachine Gun'],
  },
];

export const INITIAL_IP_TRACKER_RECORDS: IPTrackerRecord[] = [
  {
    id: 'IP-REC-001',
    ipAddress: '185.190.142.88',
    ipType: 'IPv4',
    status: 'ACTIVE_TELEMETRY',
    subjectId: 'SUB-9082',
    fullName: 'Elena V. Rostova',
    alias: 'CIPHER_NIGHTINGALE',
    dateOfBirth: '1994-06-14',
    age: 32,
    gender: 'Female',
    villageOrDistrict: 'Nieuwmarkt',
    city: 'Amsterdam',
    country: 'Netherlands',
    postalCode: '1012 CR',
    registeredAddress: 'Kloveniersburgwal 48, Nieuwmarkt Quarter',
    isp: 'KPN Telecom B.V. Fiber Network',
    asn: 'AS1136',
    organization: 'KPN Corporate Metro Access',
    hostname: 'cpe-185-190-142-88.ams-ix.kpn.net',
    connectionType: 'FIBER_OPTIC',
    isVpnOrProxy: true,
    isTorExitNode: false,
    vpnService: 'Mullvad WireGuard Tunnel (Port 51820)',
    coordinates: {
      lat: 52.3718,
      lng: 4.9011,
      altitudeMeters: 8.5,
      accuracyRadiusMeters: 25,
      meshCellId: 'CELL-AMS-SECTOR-02B',
      nearestSurveillanceNodeId: 'NODE-RELAY-01-AMS',
      nearestSurveillanceNodeName: 'AMS-CENTRAAL-ORBITAL-RADAR',
    },
    lastTelemetryPing: new Date(Date.now() - 12000).toISOString(),
    latencyMs: 14,
    packetThroughputKbps: 3480,
    threatLevel: 'CRITICAL_CODE_RED',
    associatedMacAddress: 'F4:D4:88:9C:12:3A',
    deviceInfo: {
      deviceType: 'Encrypted ThinkPad X1 Carbon Gen 11',
      os: 'Qubes OS 4.2 / Whonix VM',
      browser: 'Tor Browser v14.0.3 (Hardened)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0',
      fingerprintHash: 'FP-SHA256-88a09bc12104',
    },
    openPorts: [22, 443, 51820, 9050],
    routeHops: [
      { hop: 1, ip: '192.168.1.1', host: 'gateway.local', latencyMs: 1.2, location: 'Local CPE - Nieuwmarkt' },
      { hop: 2, ip: '195.190.240.1', host: 'ams-cr01.kpn.net', latencyMs: 4.5, location: 'Amsterdam Centraal POP' },
      { hop: 3, ip: '80.249.208.1', host: 'ams-ix01.core.net', latencyMs: 8.2, location: 'AMS-IX Science Park' },
      { hop: 4, ip: '185.190.142.1', host: 'edge-gw.mullvad.net', latencyMs: 12.1, location: 'Relay Enclave' },
      { hop: 5, ip: '185.190.142.88', host: 'cpe-185-190-142-88.ams-ix.kpn.net', latencyMs: 14.0, location: 'Target Endpoint' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 45000).toISOString(), action: 'Biometric Gate Intercept Ping', protocol: 'TLS 1.3 / QUIC', destination: 'did:aegis:auth', bytes: 14820 },
      { timestamp: new Date(Date.now() - 110000).toISOString(), action: 'High-Frequency ATM Sync', protocol: 'ISO-8583 / HTTPS', destination: 'bank.ing.global', bytes: 8420 },
      { timestamp: new Date(Date.now() - 240000).toISOString(), action: 'Encrypted Shadowsocks Key Exchange', protocol: 'WireGuard 51820', destination: 'wg-ams-04.relays', bytes: 92400 },
    ],
  },
  {
    id: 'IP-REC-002',
    ipAddress: '194.109.6.92',
    ipType: 'IPv4',
    status: 'ACTIVE_TELEMETRY',
    subjectId: 'SUB-4410',
    fullName: 'Dr. Tariq Al-Mansoor',
    alias: 'APEX_ARCHITECT',
    dateOfBirth: '1982-11-23',
    age: 43,
    gender: 'Male',
    villageOrDistrict: 'Museumkwartier',
    city: 'Amsterdam',
    country: 'Netherlands',
    postalCode: '1071 DJ',
    registeredAddress: 'Van Baerlestraat 94, Museumkwartier District',
    isp: 'SURFnet Research High-Speed Academic Grid',
    asn: 'AS1103',
    organization: 'SURF B.V. / CWI Quantum Computing Lab',
    hostname: 'q-node-04.quantum.surf.net',
    connectionType: 'FIBER_OPTIC',
    isVpnOrProxy: false,
    isTorExitNode: false,
    coordinates: {
      lat: 52.3601,
      lng: 4.8852,
      altitudeMeters: 5.4,
      accuracyRadiusMeters: 10,
      meshCellId: 'CELL-AMS-MUSEUMPLEIN-01',
      nearestSurveillanceNodeId: 'NODE-RELAY-04-RESEARCH',
      nearestSurveillanceNodeName: 'MUSEUMPLEIN-RESEARCH-ARRAY',
    },
    lastTelemetryPing: new Date(Date.now() - 18000).toISOString(),
    latencyMs: 6,
    packetThroughputKbps: 18200,
    threatLevel: 'HIGH',
    associatedMacAddress: '3C:52:82:11:AA:99',
    deviceInfo: {
      deviceType: 'Cryptographic HSM Workstation (Custom Linux)',
      os: 'Arch Linux Hardened 6.10',
      browser: 'Chromium Enterprise v129',
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/129.0.0.0 Safari/537.36',
      fingerprintHash: 'FP-SHA256-4410aa9901bf',
    },
    openPorts: [22, 80, 443, 8443, 30303],
    routeHops: [
      { hop: 1, ip: '10.100.0.1', host: 'surf-gw.museum.lab', latencyMs: 0.8, location: 'Museumkwartier Lab' },
      { hop: 2, ip: '145.145.1.1', host: 'core01.surfnet.nl', latencyMs: 2.5, location: 'SURFnet Backbone Amsterdam' },
      { hop: 3, ip: '194.109.6.92', host: 'q-node-04.quantum.surf.net', latencyMs: 6.0, location: 'CWI Research Endpoint' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 60000).toISOString(), action: 'Quantum Key Distribution Frame', protocol: 'Kyber-1024', destination: 'node-relay-04', bytes: 345000 },
      { timestamp: new Date(Date.now() - 250000).toISOString(), action: 'Sovereign Pay Intercept Verification', protocol: 'HTTPS / JSON-RPC', destination: 'aegis.sovereign.pay', bytes: 14200 },
    ],
  },
  {
    id: 'IP-REC-003',
    ipAddress: '82.161.40.11',
    ipType: 'IPv4',
    status: 'ACTIVE_TELEMETRY',
    subjectId: 'SUB-2104',
    fullName: 'Lucas K. Vance',
    alias: 'SPECTRE_09',
    dateOfBirth: '1998-03-05',
    age: 28,
    gender: 'Male',
    villageOrDistrict: 'Jordaan',
    city: 'Amsterdam',
    country: 'Netherlands',
    postalCode: '1016 GA',
    registeredAddress: 'Prinsengracht 310, Jordaan Historical Canal Quarter',
    isp: 'VodafoneZiggo B.V. DOCSIS 3.1 Gigabit',
    asn: 'AS33915',
    organization: 'Ziggo Consumer Broadband',
    hostname: 'cm-82-161-40-11.dynamic.ziggo.nl',
    connectionType: 'FIBER_OPTIC',
    isVpnOrProxy: false,
    isTorExitNode: false,
    coordinates: {
      lat: 52.3738,
      lng: 4.8899,
      altitudeMeters: 7.2,
      accuracyRadiusMeters: 18,
      meshCellId: 'CELL-AMS-SINGEL-04',
      nearestSurveillanceNodeId: 'NODE-RELAY-02-FINANCIAL',
      nearestSurveillanceNodeName: 'DAM-SQUARE-SURVEILLANCE-HUB',
    },
    lastTelemetryPing: new Date(Date.now() - 22000).toISOString(),
    latencyMs: 18,
    packetThroughputKbps: 4200,
    threatLevel: 'GUARDED',
    associatedMacAddress: 'A0:C5:89:33:EE:12',
    deviceInfo: {
      deviceType: 'MacBook Pro 16" M3 Max',
      os: 'macOS Sonoma 14.6',
      browser: 'Safari 17.5',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Safari/17.5',
      fingerprintHash: 'FP-SHA256-2104ee1288cc',
    },
    openPorts: [443, 8080],
    routeHops: [
      { hop: 1, ip: '192.168.178.1', host: 'fritz.box', latencyMs: 1.5, location: 'Jordaan Canal Gateway' },
      { hop: 2, ip: '212.54.40.1', host: 'ams-rc01.ziggo.nl', latencyMs: 9.8, location: 'Amsterdam West Exchange' },
      { hop: 3, ip: '82.161.40.11', host: 'cm-82-161-40-11.dynamic.ziggo.nl', latencyMs: 18.0, location: 'Prinsengracht Node' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 90000).toISOString(), action: 'DID Sovereign Key Validation', protocol: 'W3C DID TLS', destination: 'did:aegis:2104', bytes: 12400 },
      { timestamp: new Date(Date.now() - 320000).toISOString(), action: 'Coffee Node Contactless Telemetry', protocol: 'NFC Pass-through', destination: 'pos.merchant.sng41', bytes: 4800 },
    ],
  },
  {
    id: 'IP-REC-004',
    ipAddress: '188.166.12.44',
    ipType: 'IPv4',
    status: 'PROXY_FLAGGED',
    subjectId: 'SUB-1029',
    fullName: 'Marcus "Ghost" Chen',
    alias: 'GHOST_SYN',
    dateOfBirth: '1991-09-17',
    age: 34,
    gender: 'Male',
    villageOrDistrict: 'Oosterdok',
    city: 'Amsterdam',
    country: 'Netherlands',
    postalCode: '1011 VX',
    registeredAddress: 'Oosterdokskade 143, Oosterdok Waterfront',
    isp: 'DigitalOcean B.V. Cloud Gateway',
    asn: 'AS14061',
    organization: 'DigitalOcean Data Center 3',
    hostname: 'ams3-vpn-egress-09.relay.net',
    connectionType: 'SECURE_VPN_TUNNEL',
    isVpnOrProxy: true,
    isTorExitNode: false,
    vpnService: 'ProtonVPN Secure Core P2P',
    coordinates: {
      lat: 52.3752,
      lng: 4.9124,
      altitudeMeters: 9.0,
      accuracyRadiusMeters: 45,
      meshCellId: 'CELL-AMS-OOSTERDOK-03',
      nearestSurveillanceNodeId: 'NODE-RELAY-03-AMS',
      nearestSurveillanceNodeName: 'OOSTERDOK-QUANTUM-RELAY',
    },
    lastTelemetryPing: new Date(Date.now() - 8000).toISOString(),
    latencyMs: 24,
    packetThroughputKbps: 6400,
    threatLevel: 'GUARDED',
    associatedMacAddress: '1E:99:32:00:1B:47',
    deviceInfo: {
      deviceType: 'System76 Lemur Pro Linux Laptop',
      os: 'Pop!_OS 22.04 LTS (Kernel 6.9.3)',
      browser: 'Brave Browser v1.68',
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Brave/1.68',
      fingerprintHash: 'FP-SHA256-1029chen884b',
    },
    openPorts: [22, 1194, 51820],
    routeHops: [
      { hop: 1, ip: '10.8.0.1', host: 'vpn.internal', latencyMs: 12.0, location: 'Proton Core Tunnel' },
      { hop: 2, ip: '188.166.12.1', host: 'ams3-gw.digitalocean.com', latencyMs: 18.5, location: 'AMS3 Data Center' },
      { hop: 3, ip: '188.166.12.44', host: 'ams3-vpn-egress-09.relay.net', latencyMs: 24.0, location: 'Oosterdok Relay' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 40000).toISOString(), action: 'Sensor Mesh Latency Jitter Burst', protocol: 'UDP / WireGuard', destination: 'node-relay-03', bytes: 48200 },
      { timestamp: new Date(Date.now() - 150000).toISOString(), action: 'Encrypted Matrix Synapse Federation', protocol: 'HTTPS / Matrix', destination: 'synapse.matrix.org', bytes: 67100 },
    ],
  },
  {
    id: 'IP-REC-005',
    ipAddress: '190.92.38.105',
    ipType: 'IPv4',
    status: 'RECENT_BURST',
    subjectId: 'FUG-FBI-02',
    fullName: 'Yulan Adonay Archaga Carias',
    alias: 'PORKY',
    dateOfBirth: '1982-02-13',
    age: 44,
    gender: 'Male',
    villageOrDistrict: 'El Progreso Village',
    city: 'San Pedro Sula',
    country: 'Honduras',
    postalCode: 'HN-21101',
    registeredAddress: 'Sector Las Minas, Caserio El Progreso',
    isp: 'Claro Honduras / Starlink Maritime Satellite Uplink',
    asn: 'AS27738',
    organization: 'Comunicaciones Celulares S.A. / Starlink Business',
    hostname: 'sat-node-99.hn.claro360.net',
    connectionType: 'SATELLITE_UPLINK',
    isVpnOrProxy: true,
    isTorExitNode: false,
    vpnService: 'Custom Encrypted Shadowsocks v2',
    coordinates: {
      lat: 15.5042,
      lng: -88.025,
      altitudeMeters: 84.0,
      accuracyRadiusMeters: 120,
      meshCellId: 'CELL-HON-SANPEDRO-08',
      nearestSurveillanceNodeId: 'SAT-ORBIT-INTERCEPT-04',
      nearestSurveillanceNodeName: 'CARIBBEAN-SURVEILLANCE-CONSTELLATION',
    },
    lastTelemetryPing: new Date(Date.now() - 85000).toISOString(),
    latencyMs: 72,
    packetThroughputKbps: 1850,
    threatLevel: 'CRITICAL_CODE_RED',
    associatedMacAddress: 'E8:40:F2:77:91:00',
    deviceInfo: {
      deviceType: 'Ruggedized Toughbook CF-33 & Iridium Go',
      os: 'Android 14 (De-Googled GrapheneOS)',
      browser: 'Vanadium / Fennec',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 Mobile',
      fingerprintHash: 'FP-SHA256-porky88410293',
    },
    openPorts: [80, 443, 8388],
    routeHops: [
      { hop: 1, ip: '192.168.100.1', host: 'dishy.starlink.com', latencyMs: 28.0, location: 'Low Earth Orbit Satellite' },
      { hop: 2, ip: '143.244.32.1', host: 'gw.mia.starlinkisp.net', latencyMs: 45.2, location: 'Miami Gateway Station' },
      { hop: 3, ip: '190.92.38.105', host: 'sat-node-99.hn.claro360.net', latencyMs: 72.0, location: 'Honduran Border Intercept' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 95000).toISOString(), action: 'Encrypted Radio Burst Intercept', protocol: 'Custom UDP 8388', destination: 'cartel.relay.hn', bytes: 18900 },
      { timestamp: new Date(Date.now() - 420000).toISOString(), action: 'GPS Satellite Ephemeris Transmission', protocol: 'Iridium SBD', destination: 'iridium.uplink.net', bytes: 512 },
    ],
  },
  {
    id: 'IP-REC-006',
    ipAddress: '108.45.192.33',
    ipType: 'IPv4',
    status: 'DORMANT_RESERVE',
    subjectId: 'FUG-FBI-03',
    fullName: 'Bhadreshkumar Chetanbhai Patel',
    alias: 'BHADRESH_PATEL',
    dateOfBirth: '1990-05-15',
    age: 36,
    gender: 'Male',
    villageOrDistrict: 'Hanover Village',
    city: 'Newark',
    country: 'United States',
    postalCode: 'NJ 07102',
    registeredAddress: '124 Raymond Blvd, Hanover Transit District',
    isp: 'Verizon Business Fios Broadband',
    asn: 'AS701',
    organization: 'MCI Communications Services, Inc. d/b/a Verizon Business',
    hostname: 'static-108-45-192-33.nwk.fios.verizon.net',
    connectionType: 'CELLULAR_5G',
    isVpnOrProxy: false,
    isTorExitNode: false,
    coordinates: {
      lat: 40.6895,
      lng: -74.1745,
      altitudeMeters: 14.0,
      accuracyRadiusMeters: 30,
      meshCellId: 'CELL-USA-NEWARK-PENN-02',
      nearestSurveillanceNodeId: 'FBI-NY-FIELD-NODE',
      nearestSurveillanceNodeName: 'NEWARK-PENN-TRANSIT-SURVEILLANCE',
    },
    lastTelemetryPing: new Date(Date.now() - 140000).toISOString(),
    latencyMs: 19,
    packetThroughputKbps: 920,
    threatLevel: 'HIGH',
    associatedMacAddress: '24:A0:74:90:55:18',
    deviceInfo: {
      deviceType: 'Prepaid Burner Samsung Galaxy A15 5G',
      os: 'Android 13',
      browser: 'Chrome Mobile 126',
      userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-A156U) AppleWebKit/537.36 Mobile',
      fingerprintHash: 'FP-SHA256-patel19900515',
    },
    openPorts: [80, 443],
    routeHops: [
      { hop: 1, ip: '10.220.14.1', host: 'cell-gw.verizonwireless.com', latencyMs: 8.5, location: 'Newark Tower #41' },
      { hop: 2, ip: '152.179.99.1', host: 'nwk-core.verizon.net', latencyMs: 14.0, location: 'Newark Fios Hub' },
      { hop: 3, ip: '108.45.192.33', host: 'static-108-45-192-33.nwk.fios.verizon.net', latencyMs: 19.0, location: 'Terminal Ingress' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 150000).toISOString(), action: 'Cash App Peer-to-Peer Transfer Query', protocol: 'HTTPS 443', destination: 'api.cash.app', bytes: 8400 },
      { timestamp: new Date(Date.now() - 600000).toISOString(), action: 'Greyhound Bus Transit Inquiry', protocol: 'HTTPS 443', destination: 'greyhound.com', bytes: 34000 },
    ],
  },
  {
    id: 'IP-REC-007',
    ipAddress: '187.189.44.19',
    ipType: 'IPv4',
    status: 'ACTIVE_TELEMETRY',
    subjectId: 'FUG-FBI-04',
    fullName: 'Alejandro Rosales Castillo',
    alias: 'ALEX_CASTILLO',
    dateOfBirth: '1998-11-26',
    age: 27,
    gender: 'Male',
    villageOrDistrict: 'Zapopan Village',
    city: 'Guadalajara',
    country: 'Mexico',
    postalCode: '45100',
    registeredAddress: 'Av. Hidalgo 340, Zapopan Centro',
    isp: 'Uninet S.A. de C.V. (Telmex Infinitum)',
    asn: 'AS8151',
    organization: 'Telmex Backbone Occidente',
    hostname: 'dsl-gdl-187-189-44-19.infinitum.net.mx',
    connectionType: 'PUBLIC_WIFI_HOTSPOT',
    isVpnOrProxy: true,
    isTorExitNode: true,
    vpnService: 'Tor Onion Routing (Orbot v17)',
    coordinates: {
      lat: 20.6597,
      lng: -103.3496,
      altitudeMeters: 1560.0,
      accuracyRadiusMeters: 60,
      meshCellId: 'CELL-MEX-JALISCO-ZAPOPAN',
      nearestSurveillanceNodeId: 'INTERPOL-MEX-BORDER-ARRAY',
      nearestSurveillanceNodeName: 'GUADALAJARA-NORTH-INTERCEPT',
    },
    lastTelemetryPing: new Date(Date.now() - 40000).toISOString(),
    latencyMs: 38,
    packetThroughputKbps: 2100,
    threatLevel: 'HIGH',
    associatedMacAddress: 'BC:D0:74:11:80:5B',
    deviceInfo: {
      deviceType: 'Motorola Moto G Power (Rooted)',
      os: 'LineageOS 21 (Android 14)',
      browser: 'Tor Browser Alpha',
      userAgent: 'Mozilla/5.0 (Android 14; Mobile; rv:128.0) Gecko/128.0 Firefox/128.0',
      fingerprintHash: 'FP-SHA256-castillo981126',
    },
    openPorts: [9001, 9050, 443],
    routeHops: [
      { hop: 1, ip: '192.168.1.254', host: 'modem-infinitum.local', latencyMs: 2.1, location: 'Zapopan Plaza Hotspot' },
      { hop: 2, ip: '200.38.192.1', host: 'gdl-core.uninet.net.mx', latencyMs: 18.4, location: 'Guadalajara Fiber Hub' },
      { hop: 3, ip: '187.189.44.19', host: 'dsl-gdl-187-189-44-19.infinitum.net.mx', latencyMs: 38.0, location: 'Tor Relay Edge' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 75000).toISOString(), action: 'Tor Circuit Establishment', protocol: 'TLS 1.3 / ORPort', destination: 'tor.middle.node.de', bytes: 94000 },
      { timestamp: new Date(Date.now() - 300000).toISOString(), action: 'WhatsApp VoIP Encrypted Call', protocol: 'SRTP / UDP', destination: 'e14.whatsapp.net', bytes: 512000 },
    ],
  },
  {
    id: 'IP-REC-008',
    ipAddress: '85.24.190.62',
    ipType: 'IPv4',
    status: 'ACTIVE_TELEMETRY',
    subjectId: 'SUB-8812',
    fullName: 'Sofia Lindqvist',
    alias: 'CIPHER_OWL',
    dateOfBirth: '1996-08-20',
    age: 30,
    gender: 'Female',
    villageOrDistrict: 'Gamla Stan',
    city: 'Stockholm',
    country: 'Sweden',
    postalCode: '111 28',
    registeredAddress: 'Österlånggatan 22, Gamla Stan Historical Island',
    isp: 'Telia Company AB Nordic Core',
    asn: 'AS3301',
    organization: 'Telia Sverige Broadband Fiber',
    hostname: 'cpe-85-24-190-62.stockholm.telia.se',
    connectionType: 'FIBER_OPTIC',
    isVpnOrProxy: false,
    isTorExitNode: false,
    coordinates: {
      lat: 59.3251,
      lng: 18.0711,
      altitudeMeters: 12.0,
      accuracyRadiusMeters: 15,
      meshCellId: 'CELL-SWE-STHLM-OLDTOWN-01',
      nearestSurveillanceNodeId: 'NORDIC-EUROPOL-RELAY-08',
      nearestSurveillanceNodeName: 'STOCKHOLM-CENTRAL-TELEMETRY',
    },
    lastTelemetryPing: new Date(Date.now() - 25000).toISOString(),
    latencyMs: 11,
    packetThroughputKbps: 12800,
    threatLevel: 'LOW',
    associatedMacAddress: '48:D7:05:88:C1:22',
    deviceInfo: {
      deviceType: 'Dell XPS 15 9530',
      os: 'Ubuntu 24.04 LTS',
      browser: 'Firefox Developer Edition 129',
      userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0',
      fingerprintHash: 'FP-SHA256-lindqvist960820',
    },
    openPorts: [22, 443, 8000],
    routeHops: [
      { hop: 1, ip: '192.168.1.1', host: 'telia-router.local', latencyMs: 1.0, location: 'Gamla Stan CPE' },
      { hop: 2, ip: '81.228.84.1', host: 'sth-cr01.telia.net', latencyMs: 5.2, location: 'Stockholm Core' },
      { hop: 3, ip: '85.24.190.62', host: 'cpe-85-24-190-62.stockholm.telia.se', latencyMs: 11.0, location: 'Secure Workstation' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 40000).toISOString(), action: 'GitHub Sovereign Contract Push', protocol: 'SSH Port 22', destination: 'github.com', bytes: 124000 },
      { timestamp: new Date(Date.now() - 180000).toISOString(), action: 'E2EE Signal Messenger Sync', protocol: 'HTTPS / WebSockets', destination: 'chat.signal.org', bytes: 14200 },
    ],
  },
  {
    id: 'IP-REC-009',
    ipAddress: '178.63.88.210',
    ipType: 'IPv4',
    status: 'RECENT_BURST',
    subjectId: 'SUB-6502',
    fullName: 'Klaus Becker',
    alias: 'IRON_HELM',
    dateOfBirth: '1985-07-08',
    age: 41,
    gender: 'Male',
    villageOrDistrict: 'Kreuzberg',
    city: 'Berlin',
    country: 'Germany',
    postalCode: '10961',
    registeredAddress: 'Bergmannstraße 102, Kreuzberg District',
    isp: 'Hetzner Online GmbH Dedicated Data Backbone',
    asn: 'AS24940',
    organization: 'Hetzner Cloud Falkenstein / Berlin Peer',
    hostname: 'static.210.88.63.178.clients.your-server.de',
    connectionType: 'FIBER_OPTIC',
    isVpnOrProxy: false,
    isTorExitNode: false,
    coordinates: {
      lat: 52.4891,
      lng: 13.3888,
      altitudeMeters: 38.0,
      accuracyRadiusMeters: 20,
      meshCellId: 'CELL-GER-BERLIN-KREUZBERG',
      nearestSurveillanceNodeId: 'BKA-BERLIN-INTERCEPT-02',
      nearestSurveillanceNodeName: 'BERLIN-SOUTH-RADAR-GRID',
    },
    lastTelemetryPing: new Date(Date.now() - 50000).toISOString(),
    latencyMs: 16,
    packetThroughputKbps: 8400,
    threatLevel: 'ELEVATED',
    associatedMacAddress: '90:FB:A6:44:21:77',
    deviceInfo: {
      deviceType: 'Custom Water-Cooled Server Tower',
      os: 'Debian 12 Bookworm',
      browser: 'Firefox ESR 115',
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Firefox/115.0',
      fingerprintHash: 'FP-SHA256-becker850708',
    },
    openPorts: [22, 80, 443, 6443, 9100],
    routeHops: [
      { hop: 1, ip: '10.0.0.1', host: 'hetzner-switch.local', latencyMs: 0.9, location: 'Kreuzberg Node' },
      { hop: 2, ip: '213.239.245.1', host: 'core-berlin.hetzner.com', latencyMs: 7.4, location: 'DE-CIX Berlin Exchange' },
      { hop: 3, ip: '178.63.88.210', host: 'static.210.88.63.178.clients.your-server.de', latencyMs: 16.0, location: 'Dedicated Server' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 80000).toISOString(), action: 'Kubernetes Cluster Telemetry Beacon', protocol: 'gRPC / TLS', destination: 'k8s.api.internal', bytes: 64000 },
      { timestamp: new Date(Date.now() - 210000).toISOString(), action: 'Merkle Audit DAG Verification Check', protocol: 'JSON-RPC 8545', destination: 'node.aegis.audit', bytes: 21500 },
    ],
  },
  {
    id: 'IP-REC-010',
    ipAddress: '151.88.204.77',
    ipType: 'IPv4',
    status: 'ACTIVE_TELEMETRY',
    subjectId: 'SUB-3199',
    fullName: 'Mateo Rossi',
    alias: 'CYBER_VIPER',
    dateOfBirth: '1988-04-11',
    age: 38,
    gender: 'Male',
    villageOrDistrict: 'Trastevere Village',
    city: 'Rome',
    country: 'Italy',
    postalCode: '00153',
    registeredAddress: 'Via della Lungaretta 44, Rione Trastevere',
    isp: 'Telecom Italia Sparkle 5G Ultra',
    asn: 'AS3269',
    organization: 'TIM S.p.A. Consumer Mobile',
    hostname: 'host-151-88-204-77.retail.telecomitalia.it',
    connectionType: 'CELLULAR_5G',
    isVpnOrProxy: true,
    isTorExitNode: false,
    vpnService: 'ExpressVPN Lightway Protocol',
    coordinates: {
      lat: 41.8883,
      lng: 12.4707,
      altitudeMeters: 22.0,
      accuracyRadiusMeters: 35,
      meshCellId: 'CELL-ITA-ROMA-TRASTEVERE',
      nearestSurveillanceNodeId: 'INTERPOL-MED-GATEWAY-09',
      nearestSurveillanceNodeName: 'ROMA-CAPITALE-SECURITY-HUB',
    },
    lastTelemetryPing: new Date(Date.now() - 35000).toISOString(),
    latencyMs: 27,
    packetThroughputKbps: 5120,
    threatLevel: 'GUARDED',
    associatedMacAddress: 'D2:18:90:3A:4F:98',
    deviceInfo: {
      deviceType: 'iPhone 15 Pro Max',
      os: 'iOS 17.6',
      browser: 'Mobile Safari 17.5',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1',
      fingerprintHash: 'FP-SHA256-rossi880411',
    },
    openPorts: [443, 8443],
    routeHops: [
      { hop: 1, ip: '10.55.20.1', host: 'tim-5g-tower.roma.it', latencyMs: 8.2, location: 'Trastevere Cellular Sentry' },
      { hop: 2, ip: '195.130.224.1', host: 'rom-cr02.sparkle.it', latencyMs: 18.0, location: 'Rome NAMEX Hub' },
      { hop: 3, ip: '151.88.204.77', host: 'host-151-88-204-77.retail.telecomitalia.it', latencyMs: 27.0, location: 'Cellular Terminal' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 60000).toISOString(), action: 'Encrypted Telegram MTProto Session', protocol: 'TCP 443 MTProto', destination: '149.154.167.50', bytes: 84000 },
      { timestamp: new Date(Date.now() - 350000).toISOString(), action: 'SWIFT Intercept Transaction Ping', protocol: 'HTTPS', destination: 'unicredit.secure.it', bytes: 9200 },
    ],
  },
  {
    id: 'IP-REC-011',
    ipAddress: '185.220.101.4',
    ipType: 'IPv4',
    status: 'PROXY_FLAGGED',
    subjectId: 'FUG-EUR-01',
    fullName: 'Jos Leijdekkers',
    alias: 'BOLLE_JOS',
    dateOfBirth: '1991-05-29',
    age: 35,
    gender: 'Male',
    villageOrDistrict: 'Palm Jumeirah Village',
    city: 'Dubai',
    country: 'United Arab Emirates',
    postalCode: 'DXB-4491',
    registeredAddress: 'Frond N Villa Compound 18, Palm Jumeirah',
    isp: 'Emirates Integrated Telecommunications Company (du)',
    asn: 'AS35819',
    organization: 'du Commercial Fiber & Satellite Mesh',
    hostname: 'tor-exit-uae-node9.relays.onion',
    connectionType: 'SECURE_VPN_TUNNEL',
    isVpnOrProxy: true,
    isTorExitNode: true,
    vpnService: 'Multi-hop Tor Exit + Double Shadowsocks',
    coordinates: {
      lat: 25.1124,
      lng: 55.1390,
      altitudeMeters: 6.0,
      accuracyRadiusMeters: 350,
      meshCellId: 'CELL-UAE-DUBAI-PALM-FROND',
      nearestSurveillanceNodeId: 'EUROPOL-GULF-LIAISON-NODE',
      nearestSurveillanceNodeName: 'DUBAI-MARITIME-RADAR-GATEWAY',
    },
    lastTelemetryPing: new Date(Date.now() - 110000).toISOString(),
    latencyMs: 98,
    packetThroughputKbps: 1420,
    threatLevel: 'CRITICAL_CODE_RED',
    associatedMacAddress: '7A:91:02:88:BB:EE',
    deviceInfo: {
      deviceType: 'Encrypted Toughpad FZ-G2 & Thuraya Marine Satellite Terminal',
      os: 'Tails OS 6.5 (Amnesic Live System)',
      browser: 'Tor Browser v14.0.3',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0',
      fingerprintHash: 'FP-SHA256-leijdekkers910529',
    },
    openPorts: [443, 9001, 9050, 22000],
    routeHops: [
      { hop: 1, ip: '192.168.88.1', host: 'thuraya.satellite.marine', latencyMs: 45.0, location: 'Palm Jumeirah Marine Terminal' },
      { hop: 2, ip: '94.200.1.1', host: 'dxb-cr01.du.ae', latencyMs: 65.2, location: 'Dubai Internet City POP' },
      { hop: 3, ip: '185.220.101.4', host: 'tor-exit-uae-node9.relays.onion', latencyMs: 98.0, location: 'Tor Onion Exit Gateway' },
    ],
    recentActivity: [
      { timestamp: new Date(Date.now() - 120000).toISOString(), action: 'Maritime Satellite Relay Encryption Ping', protocol: 'Custom UDP 22000', destination: 'supercartel.sat.relay', bytes: 245000 },
      { timestamp: new Date(Date.now() - 480000).toISOString(), action: 'Tether Gold (XAUt) Multi-Sig Authorization', protocol: 'Ethereum JSON-RPC 8545', destination: 'infura.io', bytes: 18200 },
    ],
  },
];

